# Generated by Django 4.2.7 on 2023-12-04 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_rename_joingdate_user_joiningdate_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joiningDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
